import React from 'react';
import { motion } from 'framer-motion';
import { ArrowLeft, ShieldCheck, FileText, UserCircle } from 'lucide-react';

const LegalWrapper = ({ title, children, setView }) => (
  <div style={{ background: '#0f0f1a', color: 'white', minHeight: '100vh', padding: '60px 40px', fontFamily: 'Inter, sans-serif' }}>
    <div style={{ maxWidth: '800px', margin: '0 auto' }}>
      <button 
        onClick={() => setView('landing')} 
        style={{ background: 'none', border: 'none', color: '#3a86ff', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '40px', fontSize: '1.1rem' }}
      >
        <ArrowLeft size={20} /> Back to Sparks
      </button>
      <h1 style={{ fontSize: '3rem', fontWeight: 800, marginBottom: '40px', borderBottom: '2px solid rgba(255,255,255,0.1)', paddingBottom: '20px' }}>
        {title}
      </h1>
      <div style={{ lineHeight: '1.8', opacity: 0.9, fontSize: '1.1rem' }}>
        {children}
      </div>
    </div>
  </div>
);

export const PrivacyPolicy = ({ setView }) => (
  <LegalWrapper title="Privacy Policy" setView={setView}>
    <section>
      <h2 style={{ color: '#3a86ff' }}>1. Our Commitment to Kids' Safety</h2>
      <p>Sparks is built from the ground up to be a safe, creative haven for children. We are strictly compliant with the Children’s Online Privacy Protection Act (COPPA). We do not sell, rent, or trade any personal data of children.</p>
    </section>
    
    <section style={{ marginTop: '30px' }}>
      <h2 style={{ color: '#3a86ff' }}>2. Information We Collect</h2>
      <p>We do not collect personal identifiers (like real names or addresses) from child users. We only collect anonymized interaction data (like voice commands used to generate games) to improve the AI experience. Any data collected from parents during subscription is encrypted and never shared.</p>
    </section>

    <section style={{ marginTop: '30px' }}>
      <h2 style={{ color: '#3a86ff' }}>3. How We Use Data</h2>
      <p>Data is used exclusively to:
        <ul style={{ marginTop: '10px' }}>
          <li>Power the generative AI creative engines (Games, Art, Video).</li>
          <li>Ensure safety filters are functioning correctly.</li>
          <li>Provide parents with visibility into their child's creative journey.</li>
        </ul>
      </p>
    </section>

    <section style={{ marginTop: '30px', padding: '20px', background: 'rgba(58, 134, 255, 0.1)', borderRadius: '15px' }}>
      <h3>🔒 No Third-Party Tracking</h3>
      <p>We do not allow third-party advertising or tracking on Sparks. Your child's creativity is private and secure.</p>
    </section>
  </LegalWrapper>
);

export const TermsOfService = ({ setView }) => (
  <LegalWrapper title="Terms of Service" setView={setView}>
    <section>
      <h2 style={{ color: '#ffbe0b' }}>1. Acceptance of Terms</h2>
      <p>By using Sparks, you agree to these terms. As a parent or guardian, you are responsible for supervising your child's use of the platform.</p>
    </section>

    <section style={{ marginTop: '30px' }}>
      <h2 style={{ color: '#ffbe0b' }}>2. Creative Ownership</h2>
      <p>Every game, picture, and video generated by your child on Sparks is theirs to enjoy. However, users may not use Sparks to generate harmful, illegal, or inappropriate content.</p>
    </section>

    <section style={{ marginTop: '30px' }}>
      <h2 style={{ color: '#ffbe0b' }}>3. Magic Credits & Subscriptions</h2>
      <p>Subscriptions provide access to high-end "Cloud Brain" features. Credits are consumed based on the complexity of the magic being performed. All sales are final, but we offer a "Magic Satisfaction" guarantee—contact support if you have any issues!</p>
    </section>

    <section style={{ marginTop: '30px' }}>
      <h2 style={{ color: '#ffbe0b' }}>4. Safety Strike System</h2>
      <p>To keep the galaxy safe, Spark uses an automated safety monitor. Repeated attempts to bypass filters may result in a temporary "Cool Down" period for the account.</p>
    </section>
  </LegalWrapper>
);

export const AboutUs = ({ setView }) => (
  <LegalWrapper title="About Sparks" setView={setView}>
    <section style={{ textAlign: 'center', marginBottom: '60px' }}>
      <ShieldCheck size={80} color="#3a86ff" style={{ margin: '0 auto 20px' }} />
      <p style={{ fontSize: '1.5rem', fontWeight: 600 }}>We are on a mission to turn every child into a Creator.</p>
    </section>

    <p>Sparks was founded by a team of engineers and parents who realized that the future of technology belongs to the makers. We saw that while AI was becoming powerful, it wasn't always safe or accessible for the most curious minds in the world—kids.</p>
    
    <p style={{ marginTop: '20px' }}>Our platform uses a unique "Walled Garden" architecture. We take the world's most powerful AI models and wrap them in a layer of safety, creativity, and fun. We don't just want kids to use AI; we want them to command it.</p>

    <div style={{ marginTop: '40px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
      <div className="glass" style={{ padding: '20px' }}>
        <h4>Based in the Cloud</h4>
        <p style={{ fontSize: '0.9rem', opacity: 0.7 }}>Powered by Google Cloud's secure infrastructure to ensure 99.9% magic uptime.</p>
      </div>
      <div className="glass" style={{ padding: '20px' }}>
        <h4>Maker-First</h4>
        <p style={{ fontSize: '0.9rem', opacity: 0.7 }}>Every feature we build is designed to encourage building over consuming.</p>
      </div>
    </div>
  </LegalWrapper>
);
